package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

type Config struct {
	Verbose bool `mapstructure:"verbose"`

	// KeyType controls the temporary SSH keypair generated by ssh-vend-local.
	// Supported values: ed25519, rsa.
	KeyType string `mapstructure:"key_type"`

	// Profile is sent to the privileged signer. The signer owns the meaning of
	// the profile, including principal, signing key, max TTL, source restrictions,
	// and certificate options.
	Profile string `mapstructure:"profile"`

	// TTL is a requested certificate lifetime. The signer may clamp or reject it
	// according to profile policy.
	TTL string `mapstructure:"ttl"`

	// Identity is a requested certificate KeyId/comment. The signer may accept,
	// sanitize, rewrite, or reject it according to policy.
	Identity string `mapstructure:"identity"`

	// SignerCommand is the external signer command. It usually runs through sudo.
	//
	// Example:
	//   ["sudo", "-n", "-u", "ssh-vend-signer", "/usr/local/libexec/ssh-vend-local-signer"]
	SignerCommand []string `mapstructure:"signer_command"`

	// RuntimeDir is optional and mainly useful for debugging. If empty,
	// ssh-vend-local creates and removes a temporary runtime directory.
	RuntimeDir string `mapstructure:"runtime_dir"`
}

func defaultConfig() Config {
	return Config{
		Verbose: false,

		KeyType: "ed25519",
		Profile: "default",
		TTL:     "15m",

		SignerCommand: []string{
			"sudo",
			"-n",
			"-u",
			"ssh-vend-signer",
			"/usr/local/libexec/ssh-vend-local-signer",
		},
	}
}

func LoadConfig(flags *pflag.FlagSet) (Config, error) {
	cfg := defaultConfig()

	v := viper.New()
	v.SetEnvPrefix("SSH_VEND_LOCAL")
	v.SetEnvKeyReplacer(strings.NewReplacer("-", "_", ".", "_"))
	v.AutomaticEnv()

	// Defaults are the lowest-priority values. They apply only when a setting is
	// not provided by environment variable or command-line flag.
	seedDefaults(v, cfg)

	if err := bindFlags(v, flags); err != nil {
		return cfg, err
	}

	if err := v.Unmarshal(&cfg); err != nil {
		return cfg, fmt.Errorf("unmarshal config: %w", err)
	}

	if err := cfg.expandPaths(); err != nil {
		return cfg, err
	}

	if err := cfg.Validate(); err != nil {
		return cfg, err
	}

	return cfg, nil
}

func (c *Config) Validate() error {
	switch c.KeyType {
	case "", "ed25519", "rsa":
	default:
		return fmt.Errorf("unsupported key_type %q", c.KeyType)
	}

	if c.KeyType == "" {
		c.KeyType = "ed25519"
	}

	if c.Profile == "" {
		c.Profile = "default"
	}

	if c.TTL == "" {
		c.TTL = "15m"
	}

	if len(c.SignerCommand) == 0 {
		return fmt.Errorf("signer_command is required")
	}

	if strings.TrimSpace(c.SignerCommand[0]) == "" {
		return fmt.Errorf("signer_command executable is required")
	}

	return nil
}

func (c *Config) expandPaths() error {
	var err error

	if c.RuntimeDir != "" {
		c.RuntimeDir, err = expandPath(c.RuntimeDir)
		if err != nil {
			return fmt.Errorf("expand runtime_dir: %w", err)
		}
	}

	return nil
}

func seedDefaults(v *viper.Viper, d Config) {
	v.SetDefault("verbose", d.Verbose)
	v.SetDefault("key_type", d.KeyType)
	v.SetDefault("profile", d.Profile)
	v.SetDefault("ttl", d.TTL)
	v.SetDefault("identity", d.Identity)
	v.SetDefault("signer_command", d.SignerCommand)
	v.SetDefault("runtime_dir", d.RuntimeDir)
}

func bindFlags(v *viper.Viper, flags *pflag.FlagSet) error {
	for _, name := range []string{
		"verbose",
		"key-type",
		"profile",
		"ttl",
		"identity",
		"signer-command",
		"runtime-dir",
	} {
		flag := flags.Lookup(name)
		if flag == nil {
			continue
		}

		configKey := strings.ReplaceAll(name, "-", "_")
		if err := v.BindPFlag(configKey, flag); err != nil {
			return fmt.Errorf("bind flag %q: %w", name, err)
		}
	}

	return nil
}

func expandPath(path string) (string, error) {
	if path == "" {
		return "", nil
	}

	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("resolve home directory: %w", err)
		}

		switch {
		case path == "~":
			path = home
		case strings.HasPrefix(path, "~/"):
			path = filepath.Join(home, strings.TrimPrefix(path, "~/"))
		default:
			return "", fmt.Errorf("unsupported home path expansion %q", path)
		}
	}

	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("make absolute path %q: %w", path, err)
	}

	return abs, nil
}
